// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOYg5EuadbEu-RIIIPeaFynwGdF6pVjck',
    appId: '1:10328542517:web:0437e2af15f429a5c9507c',
    messagingSenderId: '10328542517',
    projectId: 'iotgreen-d0bab',
    authDomain: 'iotgreen-d0bab.firebaseapp.com',
    databaseURL: 'https://iotgreen-d0bab-default-rtdb.firebaseio.com',
    storageBucket: 'iotgreen-d0bab.appspot.com',
    measurementId: 'G-ZL85R6MSHR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3xaIC9ReQ2T0JTJbh9MFXY-qszvrRoug',
    appId: '1:10328542517:android:92df3def78c73d4ec9507c',
    messagingSenderId: '10328542517',
    projectId: 'iotgreen-d0bab',
    databaseURL: 'https://iotgreen-d0bab-default-rtdb.firebaseio.com',
    storageBucket: 'iotgreen-d0bab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClIJ4DOhmE2gzLjTzHK2HwAsgr06m-FU4',
    appId: '1:10328542517:ios:5a44181c98e2a6fec9507c',
    messagingSenderId: '10328542517',
    projectId: 'iotgreen-d0bab',
    databaseURL: 'https://iotgreen-d0bab-default-rtdb.firebaseio.com',
    storageBucket: 'iotgreen-d0bab.appspot.com',
    iosClientId: '10328542517-56buuv92ff7hf29mr7904m7a8a5o0dlo.apps.googleusercontent.com',
    iosBundleId: 'com.example.greenhouseApp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClIJ4DOhmE2gzLjTzHK2HwAsgr06m-FU4',
    appId: '1:10328542517:ios:9247cf16196eb647c9507c',
    messagingSenderId: '10328542517',
    projectId: 'iotgreen-d0bab',
    databaseURL: 'https://iotgreen-d0bab-default-rtdb.firebaseio.com',
    storageBucket: 'iotgreen-d0bab.appspot.com',
    iosClientId: '10328542517-c2nsp44mcbahqaq0pc5lssv2vdg84td7.apps.googleusercontent.com',
    iosBundleId: 'com.example.greenhouseApp2.RunnerTests',
  );
}
